In [17]:
import pandas as pd
data=pd.read_csv("googleplaystore.csv")

In [18]:
data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [19]:
data.shape

(10841, 13)

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [21]:
data.describe(include= "all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
App,10841,9660,ROBLOX,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,10841,34,FAMILY,1972,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rating,9367.0,NaN,NaN,NaN,4.193338,0.537431,1.0,4.0,4.3,4.5,19.0
Reviews,10841,6002,0,596,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Size,10841,462,Varies with device,1695,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Installs,10841,22,"1,000,000+",1579,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type,10840,3,Free,10039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Price,10841,93,0,10040,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Content Rating,10840,6,Everyone,8714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Genres,10841,120,Tools,842,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Last Updated,10841,1378,"August 3, 2018",326,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Current Ver,10833,2832,Varies with device,1459,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Android Ver,10838,33,4.1 and up,2451,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
import numpy as np
data["Size"] = data["Size"].str.replace("M","000")
data["Size"] = data["Size"].str.replace("k","")
data["Size"] = data["Size"].str.replace("Varies with device",str(np.nan))

In [23]:
data["Size"].unique()

array(['19000', '14000', '8.7000', '25000', '2.8000', '5.6000', '29000',
       '33000', '3.1000', '28000', '12000', '20000', '21000', '37000',
       '2.7000', '5.5000', '17000', '39000', '31000', '4.2000', '7.0000',
       '23000', '6.0000', '6.1000', '4.6000', '9.2000', '5.2000', '11000',
       '24000', 'nan', '9.4000', '15000', '10000', '1.2000', '26000',
       '8.0000', '7.9000', '56000', '57000', '35000', '54000', '201',
       '3.6000', '5.7000', '8.6000', '2.4000', '27000', '2.5000', '16000',
       '3.4000', '8.9000', '3.9000', '2.9000', '38000', '32000', '5.4000',
       '18000', '1.1000', '2.2000', '4.5000', '9.8000', '52000', '9.0000',
       '6.7000', '30000', '2.6000', '7.1000', '3.7000', '22000', '7.4000',
       '6.4000', '3.2000', '8.2000', '9.9000', '4.9000', '9.5000',
       '5.0000', '5.9000', '13000', '73000', '6.8000', '3.5000', '4.0000',
       '2.3000', '7.2000', '2.1000', '42000', '7.3000', '9.1000', '55000',
       '23', '6.5000', '1.5000', '7.5000', '51000', '41000', '48000',
       '8.5000', '46000', '8.3000', '4.3000', '4.7000', '3.3000', '40000',
       '7.8000', '8.8000', '6.6000', '5.1000', '61000', '66000', '79',
       '8.4000', '118', '44000', '695', '1.6000', '6.2000', '18', '53000',
       '1.4000', '3.0000', '5.8000', '3.8000', '9.6000', '45000', '63000',
       '49000', '77000', '4.4000', '4.8000', '70000', '6.9000', '9.3000',
       '10.0000', '8.1000', '36000', '84000', '97000', '2.0000', '1.9000',
       '1.8000', '5.3000', '47000', '556', '526', '76000', '7.6000',
       '59000', '9.7000', '78000', '72000', '43000', '7.7000', '6.3000',
       '334', '34000', '93000', '65000', '79000', '100000', '58000',
       '50000', '68000', '64000', '67000', '60000', '94000', '232',
       '99000', '624', '95000', '8.5', '41', '292', '11', '80000',
       '1.7000', '74000', '62000', '69000', '75000', '98000', '85000',
       '82000', '96000', '87000', '71000', '86000', '91000', '81000',
       '92000', '83000', '88000', '704', '862', '899', '378', '266',
       '375', '1.3000', '975', '980', '4.1000', '89000', '696', '544',
       '525', '920', '779', '853', '720', '713', '772', '318', '58',
       '241', '196', '857', '51', '953', '865', '251', '930', '540',
       '313', '746', '203', '26', '314', '239', '371', '220', '730',
       '756', '91', '293', '17', '74', '14', '317', '78', '924', '902',
       '818', '81', '939', '169', '45', '475', '965', '90000', '545',
       '61', '283', '655', '714', '93', '872', '121', '322', '1.0000',
       '976', '172', '238', '549', '206', '954', '444', '717', '210',
       '609', '308', '705', '306', '904', '473', '175', '350', '383',
       '454', '421', '70', '812', '442', '842', '417', '412', '459',
       '478', '335', '782', '721', '430', '429', '192', '200', '460',
       '728', '496', '816', '414', '506', '887', '613', '243', '569',
       '778', '683', '592', '319', '186', '840', '647', '191', '373',
       '437', '598', '716', '585', '982', '222', '219', '55', '948',
       '323', '691', '511', '951', '963', '25', '554', '351', '27', '82',
       '208', '913', '514', '551', '29', '103', '898', '743', '116',
       '153', '209', '353', '499', '173', '597', '809', '122', '411',
       '400', '801', '787', '237', '50', '643', '986', '97', '516', '837',
       '780', '961', '269', '20', '498', '600', '749', '642', '881', '72',
       '656', '601', '221', '228', '108', '940', '176', '33', '663', '34',
       '942', '259', '164', '458', '245', '629', '28', '288', '775',
       '785', '636', '916', '994', '309', '485', '914', '903', '608',
       '500', '54', '562', '847', '957', '688', '811', '270', '48', '329',
       '523', '921', '874', '981', '784', '280', '24', '518', '754',
       '892', '154', '860', '364', '387', '626', '161', '879', '39',
       '970', '170', '141', '160', '144', '143', '190', '376', '193',
       '246', '73', '658', '992', '253', '420', '404', '1,000+', '470',
       '226', '240', '89', '234', '257', '861', '467', '157', '44', '676',
       '67', '552', '885', '1020', '582', '619'], dtype=object)

In [24]:
data["Size"].dtype

dtype('O')

In [54]:
data = data.drop(data[data["Size"]=='1,000+'].index)
data["Size"] = data["Size"].astype("float")

In [26]:
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [27]:
data["Rating"].unique()
data["Rating"] = data["Rating"].astype("float")

In [29]:
data["Reviews"].astype("float")

0           159.0
1           967.0
2         87510.0
3        215644.0
4           967.0
           ...
10836        38.0
10837         4.0
10838         3.0
10839       114.0
10840    398307.0
Name: Reviews, Length: 10840, dtype: float64

In [32]:
data["Installs"].unique()
replace = ["+",","]
for i in replace:
    data["Installs"] = data["Installs"].str.replace(i,"")

C:\Users\Admin\AppData\Local\Temp\ipykernel_3296\3196821077.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data["Installs"] = data["Installs"].str.replace(i,"")

In [52]:
data["Installs"].unique()
data["Installs"] = data["Installs"].astype("float")

In [38]:
data["Type"].unique()
data["Type"]=data["Type"].astype("str")

In [45]:
data["Price"].unique()
data["Price"] = data["Price"].str.replace("$","")
data["Price"].unique()

C:\Users\Admin\AppData\Local\Temp\ipykernel_3296\2572330180.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data["Price"] = data["Price"].str.replace("$","")

array(['0', '4.99', '3.99', '6.99', '1.49', '2.99', '7.99', '5.99',
       '3.49', '1.99', '9.99', '7.49', '0.99', '9.00', '5.49', '10.00',
       '24.99', '11.99', '79.99', '16.99', '14.99', '1.00', '29.99',
       '12.99', '2.49', '10.99', '1.50', '19.99', '15.99', '33.99',
       '74.99', '39.99', '3.95', '4.49', '1.70', '8.99', '2.00', '3.88',
       '25.99', '399.99', '17.99', '400.00', '3.02', '1.76', '4.84',
       '4.77', '1.61', '2.50', '1.59', '6.49', '1.29', '5.00', '13.99',
       '299.99', '379.99', '37.99', '18.99', '389.99', '19.90', '8.49',
       '1.75', '14.00', '4.85', '46.99', '109.99', '154.99', '3.08',
       '2.59', '4.80', '1.96', '19.40', '3.90', '4.59', '15.46', '3.04',
       '4.29', '2.60', '3.28', '4.60', '28.99', '2.95', '2.90', '1.97',
       '200.00', '89.99', '2.56', '30.99', '3.61', '394.99', '1.26',
       '1.20', '1.04'], dtype=object)

In [49]:
data["Price"]=data["Price"].astype("float")

In [56]:
data.describe()

            Rating           Size      Installs         Price
count  9366.000000    9145.000000  1.084000e+04  10840.000000
mean      4.191757   19579.419913  1.546434e+07      1.027368
std       0.515219   24042.062020  8.502936e+07     15.949703
min       1.000000       1.000000  0.000000e+00      0.000000
25%       4.000000       5.600000  1.000000e+03      0.000000
50%       4.300000   13000.000000  1.000000e+05      0.000000
75%       4.500000   30000.000000  5.000000e+06      0.000000
max       5.000000  100000.000000  1.000000e+09    400.000000

In [58]:
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [63]:
data["Last Updated"] = pd.to_datetime(data["Last Updated"])
data["day"]=data["Last Updated"].dt.day
data["month"]=data["Last Updated"].dt.month
data["year"]=data["Last Updated"].dt.year

In [65]:
data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,20,6,2018

In [66]:
data.to_csv("cleaned_data.csv",index= False)